apiVersion: v1
kind: Service
metadata:
 name: frontend-angular
spec:
 type: NodePort
 selector:
   app: frontend-angular
   env: prod
 ports:
 - name: test
   protocol: TCP
   port: 80
   targetPort: 4200
   nodePort: 32222
